export const GET_PROFILES_REQUEST = "GET_PROFILES_REQUEST";
export const GET_PROFILES_SUCCESS = "GET_PROFILES_SUCCESS";
export const GET_PROFILES_FAILURE = "GET_PROFILES_FAILURE";

export const GET_PROFILES_BY_ID_REQUEST = "GET_PROFILES_BY_ID_REQUEST";
export const GET_PROFILES_BY_ID_SUCCESS = "GET_PROFILES_BY_ID_SUCCESS";
export const GET_PROFILES_BY_ID_FAILURE = "GET_PROFILES_BY_ID_FAILURE";

export const AUTHENTICATION_REQUEST = "AUTHENTICATION_REQUEST"
export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS"
export const AUTHENTICATION_FAILURE = "AUTHENTICATION_FAILURE"

export const GET_JOB_CANDIDATES_REQUEST = "GET_JOB_CANDIDATES_REQUEST"
export const GET_JOB_CANDIDATES_SUCCESS = "GET_JOB_CANDIDATES_SUCCESS"
export const GET_JOB_CANDIDATES_FAILURE = "GET_JOB_CANDIDATES_FAILURE"

export const SET_CURRENT_USER_DETAILS_REQUEST = "SET_CURRENT_USER_DETAILS_REQUEST"
export const SET_CURRENT_USER_DETAILS_SUCCESS = "SET_CURRENT_USER_DETAILS_SUCCESS"

export const SEND_MESSAGE_REQUEST = "SEND_MESSAGE_REQUEST"
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS"
export const SEND_MESSAGE_FAILURE = "SEND_MESSAGE_FAILURE"

export const BECOME_MENTOR_SUCCESS = "BECOME_MENTOR_SUCCESS"

export const LOGIN_MODAL_SUCCESS = "LOGIN_MODAL_SUCCESS"

export const CREATE_MENTOR_PROFILE_REQUEST = "CREATE_MENTOR_PROFILE_REQUEST"
export const CREATE_MENTOR_PROFILE_SUCCESS = "CREATE_MENTOR_PROFILE_SUCCESS"
export const CREATE_MENTOR_PROFILE_FAILURE = "CREATE_MENTOR_PROFILE_FAILURE"
